[2023-07-15T19:35:57.626+0000] {processor.py:157} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:35:57.626+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T19:35:57.627+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:35:57.627+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:35:57.644+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:35:57.643+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T19:35:57.647+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:35:57.774+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:35:57.774+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:sql_data_quality
[2023-07-15T19:35:57.786+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:35:57.786+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:sql_data_quality
[2023-07-15T19:35:57.796+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:35:57.795+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:sql_data_quality
[2023-07-15T19:35:57.813+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:35:57.812+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T19:35:57.827+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:35:57.827+0000] {dag.py:2763} INFO - Creating ORM DAG for sql_data_quality
[2023-07-15T19:35:57.839+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:35:57.839+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T19:35:57.859+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.237 seconds
[2023-07-15T19:36:28.664+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:36:28.672+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T19:36:28.673+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:36:28.673+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:36:28.683+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:36:28.682+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T19:36:28.685+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:36:28.712+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:36:28.712+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T19:36:28.736+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:36:28.736+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T19:36:28.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.097 seconds
[2023-07-15T19:36:59.168+0000] {processor.py:157} INFO - Started process (PID=141) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:36:59.170+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T19:36:59.171+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:36:59.170+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:36:59.184+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:36:59.183+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T19:36:59.187+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:36:59.218+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:36:59.218+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T19:36:59.242+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:36:59.242+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T19:36:59.260+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.096 seconds
[2023-07-15T19:37:29.412+0000] {processor.py:157} INFO - Started process (PID=185) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:37:29.414+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T19:37:29.415+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:37:29.415+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:37:29.428+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:37:29.427+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T19:37:29.430+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:37:29.462+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:37:29.462+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T19:37:29.490+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:37:29.490+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T19:37:29.509+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.101 seconds
[2023-07-15T19:37:59.710+0000] {processor.py:157} INFO - Started process (PID=223) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:37:59.711+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T19:37:59.711+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:37:59.711+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:37:59.722+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:37:59.721+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T19:37:59.724+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:37:59.753+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:37:59.753+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T19:37:59.777+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:37:59.777+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T19:37:59.795+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.088 seconds
[2023-07-15T19:38:29.907+0000] {processor.py:157} INFO - Started process (PID=267) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:38:29.910+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T19:38:29.910+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:38:29.910+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:38:29.921+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:38:29.921+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T19:38:29.924+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:38:29.952+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:38:29.952+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T19:38:29.978+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:38:29.978+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T19:38:29.999+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.095 seconds
[2023-07-15T19:39:00.074+0000] {processor.py:157} INFO - Started process (PID=305) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:39:00.077+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T19:39:00.078+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:39:00.078+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:39:00.091+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:39:00.090+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T19:39:00.094+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:39:00.126+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:39:00.125+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T19:39:00.150+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:39:00.150+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T19:39:00.170+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.099 seconds
[2023-07-15T19:39:30.266+0000] {processor.py:157} INFO - Started process (PID=343) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:39:30.267+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T19:39:30.268+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:39:30.268+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:39:30.280+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:39:30.279+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T19:39:30.283+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T19:39:30.315+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:39:30.315+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T19:39:30.342+0000] {logging_mixin.py:150} INFO - [2023-07-15T19:39:30.341+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T19:39:30.363+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.101 seconds
[2023-07-15T20:21:26.012+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:21:26.014+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:21:26.014+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:21:26.014+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:21:26.033+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:21:26.033+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:21:26.038+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:21:26.270+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:21:26.270+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:21:26.293+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:21:26.293+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:21:26.319+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.311 seconds
[2023-07-15T20:21:56.353+0000] {processor.py:157} INFO - Started process (PID=101) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:21:56.354+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:21:56.355+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:21:56.355+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:21:56.366+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:21:56.365+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:21:56.368+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:21:56.395+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:21:56.395+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:21:56.418+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:21:56.418+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:21:56.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.086 seconds
[2023-07-15T20:22:27.008+0000] {processor.py:157} INFO - Started process (PID=145) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:22:27.011+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:22:27.011+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:22:27.011+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:22:27.023+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:22:27.022+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:22:27.026+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:22:27.052+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:22:27.052+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:22:27.076+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:22:27.076+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:22:27.094+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.090 seconds
[2023-07-15T20:22:57.245+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:22:57.248+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:22:57.249+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:22:57.248+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:22:57.260+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:22:57.259+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:22:57.264+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:22:57.295+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:22:57.295+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:22:57.324+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:22:57.323+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:22:57.347+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.105 seconds
[2023-07-15T20:23:27.581+0000] {processor.py:157} INFO - Started process (PID=227) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:23:27.584+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:23:27.585+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:23:27.585+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:23:27.594+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:23:27.593+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:23:27.597+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:23:27.622+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:23:27.622+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:23:27.644+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:23:27.644+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:23:27.662+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.084 seconds
[2023-07-15T20:23:58.024+0000] {processor.py:157} INFO - Started process (PID=265) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:23:58.025+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:23:58.026+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:23:58.026+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:23:58.036+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:23:58.035+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:23:58.038+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:23:58.064+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:23:58.064+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:23:58.087+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:23:58.087+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:23:58.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.085 seconds
[2023-07-15T20:24:28.319+0000] {processor.py:157} INFO - Started process (PID=303) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:24:28.323+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:24:28.324+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:24:28.324+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:24:28.337+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:24:28.336+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:24:28.339+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:24:28.380+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:24:28.380+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:24:28.415+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:24:28.415+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:24:28.439+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.123 seconds
[2023-07-15T20:24:58.636+0000] {processor.py:157} INFO - Started process (PID=341) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:24:58.639+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:24:58.641+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:24:58.640+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:24:58.655+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:24:58.654+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:24:58.657+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:24:58.685+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:24:58.684+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:24:58.708+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:24:58.708+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:24:58.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.098 seconds
[2023-07-15T20:25:29.161+0000] {processor.py:157} INFO - Started process (PID=379) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:25:29.164+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:25:29.165+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:25:29.164+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:25:29.175+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:25:29.174+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:25:29.177+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:25:29.205+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:25:29.205+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:25:29.230+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:25:29.229+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:25:29.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.092 seconds
[2023-07-15T20:25:59.664+0000] {processor.py:157} INFO - Started process (PID=417) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:25:59.667+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:25:59.667+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:25:59.667+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:25:59.678+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:25:59.677+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:25:59.680+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:25:59.705+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:25:59.705+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:25:59.729+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:25:59.729+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:25:59.747+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.087 seconds
[2023-07-15T20:26:29.965+0000] {processor.py:157} INFO - Started process (PID=455) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:26:29.967+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:26:29.967+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:26:29.967+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:26:29.978+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:26:29.977+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:26:29.980+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:26:30.006+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:26:30.006+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:26:30.036+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:26:30.036+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:26:30.058+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.096 seconds
[2023-07-15T20:27:00.188+0000] {processor.py:157} INFO - Started process (PID=493) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:27:00.189+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:27:00.190+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:27:00.190+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:27:00.201+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:27:00.200+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:27:00.203+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:27:00.234+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:27:00.234+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:27:00.259+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:27:00.259+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:27:00.276+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.091 seconds
[2023-07-15T20:27:31.043+0000] {processor.py:157} INFO - Started process (PID=518) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:27:31.046+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:27:31.047+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:27:31.047+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:27:31.058+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:27:31.057+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:27:31.061+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:27:31.088+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:27:31.088+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:27:31.113+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:27:31.113+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:27:31.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.098 seconds
[2023-07-15T20:28:01.669+0000] {processor.py:157} INFO - Started process (PID=556) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:28:01.672+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:28:01.674+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:28:01.674+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:28:01.689+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:28:01.688+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:28:01.692+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:28:01.718+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:28:01.718+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:28:01.748+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:28:01.747+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:28:01.770+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.104 seconds
[2023-07-15T20:28:32.188+0000] {processor.py:157} INFO - Started process (PID=594) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:28:32.192+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:28:32.193+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:28:32.193+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:28:32.205+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:28:32.205+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:28:32.208+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:28:32.234+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:28:32.234+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:28:32.258+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:28:32.258+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:28:32.279+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.101 seconds
[2023-07-15T20:29:02.431+0000] {processor.py:157} INFO - Started process (PID=632) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:29:02.432+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:29:02.433+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:29:02.432+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:29:02.444+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:29:02.444+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:29:02.447+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:29:02.476+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:29:02.476+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:29:02.499+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:29:02.499+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:29:02.517+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.090 seconds
[2023-07-15T20:29:32.701+0000] {processor.py:157} INFO - Started process (PID=670) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:29:32.702+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:29:32.703+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:29:32.703+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:29:32.715+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:29:32.714+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:29:32.718+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:29:32.765+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:29:32.765+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:29:32.797+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:29:32.796+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:29:32.818+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.121 seconds
[2023-07-15T20:30:03.331+0000] {processor.py:157} INFO - Started process (PID=708) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:30:03.334+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:30:03.335+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:30:03.335+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:30:03.350+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:30:03.349+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:30:03.352+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:30:03.384+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:30:03.384+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:30:03.413+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:30:03.412+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:30:03.431+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.104 seconds
[2023-07-15T20:30:33.628+0000] {processor.py:157} INFO - Started process (PID=746) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:30:33.631+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:30:33.632+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:30:33.632+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:30:33.643+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:30:33.642+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:30:33.645+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:30:33.674+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:30:33.674+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:30:33.698+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:30:33.698+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:30:33.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.092 seconds
[2023-07-15T20:31:03.933+0000] {processor.py:157} INFO - Started process (PID=784) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:31:03.936+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:31:03.937+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:31:03.937+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:31:03.949+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:31:03.948+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:31:03.952+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:31:03.982+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:31:03.982+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:31:04.009+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:31:04.009+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:31:04.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.098 seconds
[2023-07-15T20:31:34.237+0000] {processor.py:157} INFO - Started process (PID=822) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:31:34.240+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:31:34.241+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:31:34.241+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:31:34.255+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:31:34.255+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:31:34.258+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:31:34.292+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:31:34.292+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:31:34.326+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:31:34.326+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:31:34.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.114 seconds
[2023-07-15T20:32:04.638+0000] {processor.py:157} INFO - Started process (PID=860) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:32:04.641+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:32:04.642+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:32:04.642+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:32:04.654+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:32:04.653+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:32:04.656+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:32:04.686+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:32:04.686+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:32:04.711+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:32:04.711+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:32:04.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.100 seconds
[2023-07-15T20:32:34.933+0000] {processor.py:157} INFO - Started process (PID=898) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:32:34.936+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:32:34.937+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:32:34.937+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:32:34.947+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:32:34.946+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:32:34.949+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:32:34.978+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:32:34.978+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:32:35.002+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:32:35.002+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:32:35.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.091 seconds
[2023-07-15T20:33:05.173+0000] {processor.py:157} INFO - Started process (PID=936) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:33:05.176+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:33:05.177+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:33:05.177+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:33:05.193+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:33:05.192+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:33:05.196+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:33:05.236+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:33:05.235+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:33:05.262+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:33:05.262+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:33:05.281+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.113 seconds
[2023-07-15T20:33:35.609+0000] {processor.py:157} INFO - Started process (PID=974) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:33:35.612+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:33:35.613+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:33:35.612+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:33:35.625+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:33:35.624+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:33:35.627+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:33:35.654+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:33:35.654+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:33:35.679+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:33:35.679+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:33:35.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.091 seconds
[2023-07-15T20:34:06.010+0000] {processor.py:157} INFO - Started process (PID=1012) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:34:06.014+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:34:06.014+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:34:06.014+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:34:06.029+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:34:06.028+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:34:06.032+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:34:06.070+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:34:06.070+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:34:06.102+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:34:06.102+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:34:06.133+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.128 seconds
[2023-07-15T20:34:36.588+0000] {processor.py:157} INFO - Started process (PID=1050) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:34:36.591+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:34:36.592+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:34:36.591+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:34:36.606+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:34:36.605+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:34:36.609+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:34:36.643+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:34:36.643+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:34:36.677+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:34:36.677+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:34:36.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.118 seconds
[2023-07-15T20:35:07.007+0000] {processor.py:157} INFO - Started process (PID=1088) to work on /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:35:07.011+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dag_select_query.py for tasks to queue
[2023-07-15T20:35:07.012+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:35:07.012+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:35:07.023+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:35:07.023+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: custom_check.sql
[2023-07-15T20:35:07.026+0000] {processor.py:836} INFO - DAG(s) dict_keys(['sql_data_quality']) retrieved from /opt/airflow/dags/dag_select_query.py
[2023-07-15T20:35:07.058+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:35:07.058+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-15T20:35:07.083+0000] {logging_mixin.py:150} INFO - [2023-07-15T20:35:07.083+0000] {dag.py:3508} INFO - Setting next_dagrun for sql_data_quality to None, run_after=None
[2023-07-15T20:35:07.108+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_select_query.py took 0.108 seconds
